# Generated by Django 5.0.1 on 2024-01-06 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Artist', models.CharField(max_length=100)),
                ('post_file', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
