# Generated by Django 5.0.1 on 2024-01-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='caption',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
