# Generated by Django 5.0.1 on 2024-01-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='artworks',
            new_name='artwork',
        ),
    ]
