# Generated by Django 5.0.1 on 2024-01-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
    ]
