# Generated by Django 5.0.2 on 2024-03-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_exhibit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibit',
            old_name='product_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='artist',
            field=models.CharField(choices=[('hacajaka', 'hacajaka'), ('oladapo', 'oladapo'), ('kwadwo', 'kwadwo'), ('massimo', 'massimo'), ('patrick', 'patrick')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.CharField(choices=[('hacajaka', 'hacajaka'), ('oladapo', 'oladapo'), ('kwadwo', 'kwadwo'), ('massimo', 'massimo'), ('patrick', 'patrick')], max_length=100),
        ),
    ]
