# Generated by Django 5.0.2 on 2024-04-02 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
