# Generated by Django 5.0.2 on 2024-04-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_org_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='tex',
            new_name='text',
        ),
    ]
