# Generated by Django 5.0.2 on 2024-04-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_tex_org_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to='insight_cover')),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
