# Generated by Django 5.0.2 on 2024-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_exhibit_artist_alter_product_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='artist',
            field=models.CharField(choices=[('hacajaka', 'hacajaka'), ('oladapo alao', 'oladapo alao'), ('kwadwo ani', 'kwadwo ani'), ('massimo wansi', 'massimo wansi'), ('Nestor Hernandez', 'Nestor Hernandez'), ('patrick tagoe-turkson', 'patrick tagoe-turkson'), ('konyo', 'konyo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.CharField(choices=[('hacajaka', 'hacajaka'), ('oladapo alao', 'oladapo alao'), ('kwadwo ani', 'kwadwo ani'), ('massimo wansi', 'massimo wansi'), ('Nestor Hernandez', 'Nestor Hernandez'), ('patrick tagoe-turkson', 'patrick tagoe-turkson'), ('konyo', 'konyo')], max_length=100),
        ),
    ]
